//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.07 at 05:32:52 PM CEST 
//


package app;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kategorie" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="kategorie_titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="kategorie_beschreibung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="kategorie_id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kategorie"
})
@XmlRootElement(name = "kategorien")
public class Kategorien {

    @XmlElement(required = true)
    protected List<Kategorien.Kategorie> kategorie;

    /**
     * Gets the value of the kategorie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kategorie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKategorie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kategorien.Kategorie }
     * 
     * 
     */
    public List<Kategorien.Kategorie> getKategorie() {
        if (kategorie == null) {
            kategorie = new ArrayList<Kategorien.Kategorie>();
        }
        return this.kategorie;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="kategorie_titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="kategorie_beschreibung" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="kategorie_id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kategorieTitel",
        "kategorieBeschreibung"
    })
    public static class Kategorie {

        @XmlElement(name = "kategorie_titel", required = true)
        protected String kategorieTitel;
        @XmlElement(name = "kategorie_beschreibung", required = true)
        protected String kategorieBeschreibung;
        @XmlAttribute(name = "kategorie_id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String kategorieId;

        /**
         * Gets the value of the kategorieTitel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKategorieTitel() {
            return kategorieTitel;
        }

        /**
         * Sets the value of the kategorieTitel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKategorieTitel(String value) {
            this.kategorieTitel = value;
        }

        /**
         * Gets the value of the kategorieBeschreibung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKategorieBeschreibung() {
            return kategorieBeschreibung;
        }

        /**
         * Sets the value of the kategorieBeschreibung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKategorieBeschreibung(String value) {
            this.kategorieBeschreibung = value;
        }

        /**
         * Gets the value of the kategorieId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKategorieId() {
            return kategorieId;
        }

        /**
         * Sets the value of the kategorieId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKategorieId(String value) {
            this.kategorieId = value;
        }

    }

}
