//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.20 at 01:47:43 PM CEST 
//


package app;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the app package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _User_QNAME = new QName("", "user");
    private final static QName _ThemesThemeAllgemeinesKategorienKategorie_QNAME = new QName("", "kategorie");
    private final static QName _ThemesThemeAllgemeinesGenresGenre_QNAME = new QName("", "genre");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: app
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Themes }
     * 
     */
    public Themes createThemes() {
        return new Themes();
    }

    /**
     * Create an instance of {@link Beschreibung }
     * 
     */
    public Beschreibung createBeschreibung() {
        return new Beschreibung();
    }

    /**
     * Create an instance of {@link Themes.Theme }
     * 
     */
    public Themes.Theme createThemesTheme() {
        return new Themes.Theme();
    }

    /**
     * Create an instance of {@link Themes.Theme.Interaktion }
     * 
     */
    public Themes.Theme.Interaktion createThemesThemeInteraktion() {
        return new Themes.Theme.Interaktion();
    }

    /**
     * Create an instance of {@link Themes.Theme.Interaktion.Kommentare }
     * 
     */
    public Themes.Theme.Interaktion.Kommentare createThemesThemeInteraktionKommentare() {
        return new Themes.Theme.Interaktion.Kommentare();
    }

    /**
     * Create an instance of {@link Themes.Theme.Module }
     * 
     */
    public Themes.Theme.Module createThemesThemeModule() {
        return new Themes.Theme.Module();
    }

    /**
     * Create an instance of {@link Themes.Theme.Module.Musik }
     * 
     */
    public Themes.Theme.Module.Musik createThemesThemeModuleMusik() {
        return new Themes.Theme.Module.Musik();
    }

    /**
     * Create an instance of {@link Themes.Theme.Allgemeines }
     * 
     */
    public Themes.Theme.Allgemeines createThemesThemeAllgemeines() {
        return new Themes.Theme.Allgemeines();
    }

    /**
     * Create an instance of {@link Rezept }
     * 
     */
    public Rezept createRezept() {
        return new Rezept();
    }

    /**
     * Create an instance of {@link Beschreibung.Text }
     * 
     */
    public Beschreibung.Text createBeschreibungText() {
        return new Beschreibung.Text();
    }

    /**
     * Create an instance of {@link Themes.Theme.Interaktion.Abonennten }
     * 
     */
    public Themes.Theme.Interaktion.Abonennten createThemesThemeInteraktionAbonennten() {
        return new Themes.Theme.Interaktion.Abonennten();
    }

    /**
     * Create an instance of {@link Themes.Theme.Interaktion.Kommentare.Kommentar }
     * 
     */
    public Themes.Theme.Interaktion.Kommentare.Kommentar createThemesThemeInteraktionKommentareKommentar() {
        return new Themes.Theme.Interaktion.Kommentare.Kommentar();
    }

    /**
     * Create an instance of {@link Themes.Theme.Module.Dekoration }
     * 
     */
    public Themes.Theme.Module.Dekoration createThemesThemeModuleDekoration() {
        return new Themes.Theme.Module.Dekoration();
    }

    /**
     * Create an instance of {@link Themes.Theme.Module.Outfits }
     * 
     */
    public Themes.Theme.Module.Outfits createThemesThemeModuleOutfits() {
        return new Themes.Theme.Module.Outfits();
    }

    /**
     * Create an instance of {@link Themes.Theme.Module.Catering }
     * 
     */
    public Themes.Theme.Module.Catering createThemesThemeModuleCatering() {
        return new Themes.Theme.Module.Catering();
    }

    /**
     * Create an instance of {@link Themes.Theme.Module.Locations }
     * 
     */
    public Themes.Theme.Module.Locations createThemesThemeModuleLocations() {
        return new Themes.Theme.Module.Locations();
    }

    /**
     * Create an instance of {@link Themes.Theme.Module.Musik.Song }
     * 
     */
    public Themes.Theme.Module.Musik.Song createThemesThemeModuleMusikSong() {
        return new Themes.Theme.Module.Musik.Song();
    }

    /**
     * Create an instance of {@link Themes.Theme.Allgemeines.Genres }
     * 
     */
    public Themes.Theme.Allgemeines.Genres createThemesThemeAllgemeinesGenres() {
        return new Themes.Theme.Allgemeines.Genres();
    }

    /**
     * Create an instance of {@link Themes.Theme.Allgemeines.Kategorien }
     * 
     */
    public Themes.Theme.Allgemeines.Kategorien createThemesThemeAllgemeinesKategorien() {
        return new Themes.Theme.Allgemeines.Kategorien();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user")
    public JAXBElement<String> createUser(String value) {
        return new JAXBElement<String>(_User_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "kategorie", scope = Themes.Theme.Allgemeines.Kategorien.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    public JAXBElement<String> createThemesThemeAllgemeinesKategorienKategorie(String value) {
        return new JAXBElement<String>(_ThemesThemeAllgemeinesKategorienKategorie_QNAME, String.class, Themes.Theme.Allgemeines.Kategorien.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genre", scope = Themes.Theme.Allgemeines.Genres.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    public JAXBElement<String> createThemesThemeAllgemeinesGenresGenre(String value) {
        return new JAXBElement<String>(_ThemesThemeAllgemeinesGenresGenre_QNAME, String.class, Themes.Theme.Allgemeines.Genres.class, value);
    }

}
