//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.20 at 01:47:43 PM CEST 
//


package app;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="theme" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="allgemeines">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="theme_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="genres">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="kategorien">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="kategorie" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="bewertung" default="0">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                 &lt;minInclusive value="0"/>
 *                                 &lt;maxInclusive value="5"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="theme_id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="module">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="dekoration">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="dekoration_element" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="outfits">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="outfit" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="musik">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="song" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;all>
 *                                                 &lt;element name="song_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="song_interpret" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                               &lt;/all>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="catering">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;choice>
 *                                         &lt;element name="getraenk" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
 *                                         &lt;element name="gericht" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;/choice>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="locations">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="location" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="interaktion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="abonennten">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}user" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="kommentare">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="kommentar" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element ref="{}user"/>
 *                                                 &lt;element name="uhrzeit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "theme"
})
@XmlRootElement(name = "themes")
public class Themes {

    @XmlElement(required = true)
    protected List<Themes.Theme> theme;

    /**
     * Gets the value of the theme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Themes.Theme }
     * 
     * 
     */
    public List<Themes.Theme> getTheme() {
        if (theme == null) {
            theme = new ArrayList<Themes.Theme>();
        }
        return this.theme;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="allgemeines">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="theme_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="genres">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="kategorien">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="kategorie" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="bewertung" default="0">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                       &lt;minInclusive value="0"/>
     *                       &lt;maxInclusive value="5"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="theme_id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="module">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="dekoration">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="dekoration_element" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="outfits">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="outfit" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="musik">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="song" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;all>
     *                                       &lt;element name="song_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                       &lt;element name="song_interpret" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                       &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                                     &lt;/all>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="catering">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;choice>
     *                               &lt;element name="getraenk" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
     *                               &lt;element name="gericht" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;/choice>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="locations">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="location" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="interaktion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="abonennten">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}user" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="kommentare">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="kommentar" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element ref="{}user"/>
     *                                       &lt;element name="uhrzeit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allgemeines",
        "module",
        "interaktion"
    })
    public static class Theme {

        @XmlElement(required = true)
        protected Themes.Theme.Allgemeines allgemeines;
        @XmlElement(required = true)
        protected Themes.Theme.Module module;
        @XmlElement(required = true)
        protected Themes.Theme.Interaktion interaktion;

        /**
         * Gets the value of the allgemeines property.
         * 
         * @return
         *     possible object is
         *     {@link Themes.Theme.Allgemeines }
         *     
         */
        public Themes.Theme.Allgemeines getAllgemeines() {
            return allgemeines;
        }

        /**
         * Sets the value of the allgemeines property.
         * 
         * @param value
         *     allowed object is
         *     {@link Themes.Theme.Allgemeines }
         *     
         */
        public void setAllgemeines(Themes.Theme.Allgemeines value) {
            this.allgemeines = value;
        }

        /**
         * Gets the value of the module property.
         * 
         * @return
         *     possible object is
         *     {@link Themes.Theme.Module }
         *     
         */
        public Themes.Theme.Module getModule() {
            return module;
        }

        /**
         * Sets the value of the module property.
         * 
         * @param value
         *     allowed object is
         *     {@link Themes.Theme.Module }
         *     
         */
        public void setModule(Themes.Theme.Module value) {
            this.module = value;
        }

        /**
         * Gets the value of the interaktion property.
         * 
         * @return
         *     possible object is
         *     {@link Themes.Theme.Interaktion }
         *     
         */
        public Themes.Theme.Interaktion getInteraktion() {
            return interaktion;
        }

        /**
         * Sets the value of the interaktion property.
         * 
         * @param value
         *     allowed object is
         *     {@link Themes.Theme.Interaktion }
         *     
         */
        public void setInteraktion(Themes.Theme.Interaktion value) {
            this.interaktion = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="theme_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="genres">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="kategorien">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="kategorie" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="bewertung" default="0">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *             &lt;minInclusive value="0"/>
         *             &lt;maxInclusive value="5"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="theme_id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "themeTitel",
            "genres",
            "kategorien"
        })
        public static class Allgemeines {

            @XmlElement(name = "theme_titel", required = true)
            protected Object themeTitel;
            @XmlElement(required = true)
            protected Themes.Theme.Allgemeines.Genres genres;
            @XmlElement(required = true)
            protected Themes.Theme.Allgemeines.Kategorien kategorien;
            @XmlAttribute(name = "bewertung")
            protected Integer bewertung;
            @XmlAttribute(name = "theme_id", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String themeId;

            /**
             * Gets the value of the themeTitel property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getThemeTitel() {
                return themeTitel;
            }

            /**
             * Sets the value of the themeTitel property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setThemeTitel(Object value) {
                this.themeTitel = value;
            }

            /**
             * Gets the value of the genres property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Allgemeines.Genres }
             *     
             */
            public Themes.Theme.Allgemeines.Genres getGenres() {
                return genres;
            }

            /**
             * Sets the value of the genres property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Allgemeines.Genres }
             *     
             */
            public void setGenres(Themes.Theme.Allgemeines.Genres value) {
                this.genres = value;
            }

            /**
             * Gets the value of the kategorien property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Allgemeines.Kategorien }
             *     
             */
            public Themes.Theme.Allgemeines.Kategorien getKategorien() {
                return kategorien;
            }

            /**
             * Sets the value of the kategorien property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Allgemeines.Kategorien }
             *     
             */
            public void setKategorien(Themes.Theme.Allgemeines.Kategorien value) {
                this.kategorien = value;
            }

            /**
             * Gets the value of the bewertung property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getBewertung() {
                if (bewertung == null) {
                    return  0;
                } else {
                    return bewertung;
                }
            }

            /**
             * Sets the value of the bewertung property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBewertung(Integer value) {
                this.bewertung = value;
            }

            /**
             * Gets the value of the themeId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getThemeId() {
                return themeId;
            }

            /**
             * Sets the value of the themeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setThemeId(String value) {
                this.themeId = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "genre"
            })
            public static class Genres {

                @XmlElementRef(name = "genre", type = JAXBElement.class)
                protected List<JAXBElement<String>> genre;

                /**
                 * Gets the value of the genre property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the genre property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getGenre().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<String>> getGenre() {
                    if (genre == null) {
                        genre = new ArrayList<JAXBElement<String>>();
                    }
                    return this.genre;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="kategorie" type="{http://www.w3.org/2001/XMLSchema}ID" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "kategorie"
            })
            public static class Kategorien {

                @XmlElementRef(name = "kategorie", type = JAXBElement.class)
                protected List<JAXBElement<String>> kategorie;

                /**
                 * Gets the value of the kategorie property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the kategorie property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getKategorie().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<String>> getKategorie() {
                    if (kategorie == null) {
                        kategorie = new ArrayList<JAXBElement<String>>();
                    }
                    return this.kategorie;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="abonennten">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}user" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="kommentare">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="kommentar" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element ref="{}user"/>
         *                             &lt;element name="uhrzeit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "abonennten",
            "kommentare"
        })
        public static class Interaktion {

            @XmlElement(required = true)
            protected Themes.Theme.Interaktion.Abonennten abonennten;
            @XmlElement(required = true)
            protected Themes.Theme.Interaktion.Kommentare kommentare;

            /**
             * Gets the value of the abonennten property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Interaktion.Abonennten }
             *     
             */
            public Themes.Theme.Interaktion.Abonennten getAbonennten() {
                return abonennten;
            }

            /**
             * Sets the value of the abonennten property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Interaktion.Abonennten }
             *     
             */
            public void setAbonennten(Themes.Theme.Interaktion.Abonennten value) {
                this.abonennten = value;
            }

            /**
             * Gets the value of the kommentare property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Interaktion.Kommentare }
             *     
             */
            public Themes.Theme.Interaktion.Kommentare getKommentare() {
                return kommentare;
            }

            /**
             * Sets the value of the kommentare property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Interaktion.Kommentare }
             *     
             */
            public void setKommentare(Themes.Theme.Interaktion.Kommentare value) {
                this.kommentare = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}user" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "user"
            })
            public static class Abonennten {

                protected List<String> user;

                /**
                 * Gets the value of the user property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the user property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getUser().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getUser() {
                    if (user == null) {
                        user = new ArrayList<String>();
                    }
                    return this.user;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="kommentar" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element ref="{}user"/>
             *                   &lt;element name="uhrzeit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "kommentar"
            })
            public static class Kommentare {

                protected List<Themes.Theme.Interaktion.Kommentare.Kommentar> kommentar;

                /**
                 * Gets the value of the kommentar property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the kommentar property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getKommentar().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Themes.Theme.Interaktion.Kommentare.Kommentar }
                 * 
                 * 
                 */
                public List<Themes.Theme.Interaktion.Kommentare.Kommentar> getKommentar() {
                    if (kommentar == null) {
                        kommentar = new ArrayList<Themes.Theme.Interaktion.Kommentare.Kommentar>();
                    }
                    return this.kommentar;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element ref="{}user"/>
                 *         &lt;element name="uhrzeit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "nachricht",
                    "user",
                    "uhrzeit"
                })
                public static class Kommentar {

                    @XmlElement(required = true)
                    protected String nachricht;
                    @XmlElement(required = true)
                    protected String user;
                    @XmlElement(required = true)
                    @XmlSchemaType(name = "dateTime")
                    protected XMLGregorianCalendar uhrzeit;

                    /**
                     * Gets the value of the nachricht property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNachricht() {
                        return nachricht;
                    }

                    /**
                     * Sets the value of the nachricht property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNachricht(String value) {
                        this.nachricht = value;
                    }

                    /**
                     * Gets the value of the user property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUser() {
                        return user;
                    }

                    /**
                     * Sets the value of the user property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUser(String value) {
                        this.user = value;
                    }

                    /**
                     * Gets the value of the uhrzeit property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getUhrzeit() {
                        return uhrzeit;
                    }

                    /**
                     * Sets the value of the uhrzeit property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setUhrzeit(XMLGregorianCalendar value) {
                        this.uhrzeit = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="dekoration">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="dekoration_element" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="outfits">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="outfit" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="musik">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="song" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;all>
         *                             &lt;element name="song_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                             &lt;element name="song_interpret" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *                           &lt;/all>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="catering">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;choice>
         *                     &lt;element name="getraenk" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
         *                     &lt;element name="gericht" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;/choice>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="locations">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="location" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Module {

            @XmlElement(required = true)
            protected Themes.Theme.Module.Dekoration dekoration;
            @XmlElement(required = true)
            protected Themes.Theme.Module.Outfits outfits;
            @XmlElement(required = true)
            protected Themes.Theme.Module.Musik musik;
            @XmlElement(required = true)
            protected Themes.Theme.Module.Catering catering;
            @XmlElement(required = true)
            protected Themes.Theme.Module.Locations locations;

            /**
             * Gets the value of the dekoration property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Module.Dekoration }
             *     
             */
            public Themes.Theme.Module.Dekoration getDekoration() {
                return dekoration;
            }

            /**
             * Sets the value of the dekoration property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Module.Dekoration }
             *     
             */
            public void setDekoration(Themes.Theme.Module.Dekoration value) {
                this.dekoration = value;
            }

            /**
             * Gets the value of the outfits property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Module.Outfits }
             *     
             */
            public Themes.Theme.Module.Outfits getOutfits() {
                return outfits;
            }

            /**
             * Sets the value of the outfits property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Module.Outfits }
             *     
             */
            public void setOutfits(Themes.Theme.Module.Outfits value) {
                this.outfits = value;
            }

            /**
             * Gets the value of the musik property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Module.Musik }
             *     
             */
            public Themes.Theme.Module.Musik getMusik() {
                return musik;
            }

            /**
             * Sets the value of the musik property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Module.Musik }
             *     
             */
            public void setMusik(Themes.Theme.Module.Musik value) {
                this.musik = value;
            }

            /**
             * Gets the value of the catering property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Module.Catering }
             *     
             */
            public Themes.Theme.Module.Catering getCatering() {
                return catering;
            }

            /**
             * Sets the value of the catering property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Module.Catering }
             *     
             */
            public void setCatering(Themes.Theme.Module.Catering value) {
                this.catering = value;
            }

            /**
             * Gets the value of the locations property.
             * 
             * @return
             *     possible object is
             *     {@link Themes.Theme.Module.Locations }
             *     
             */
            public Themes.Theme.Module.Locations getLocations() {
                return locations;
            }

            /**
             * Sets the value of the locations property.
             * 
             * @param value
             *     allowed object is
             *     {@link Themes.Theme.Module.Locations }
             *     
             */
            public void setLocations(Themes.Theme.Module.Locations value) {
                this.locations = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;choice>
             *           &lt;element name="getraenk" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
             *           &lt;element name="gericht" type="{}rezept" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;/choice>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "getraenk",
                "gericht"
            })
            public static class Catering {

                protected List<Rezept> getraenk;
                protected List<Rezept> gericht;

                /**
                 * Gets the value of the getraenk property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the getraenk property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getGetraenk().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Rezept }
                 * 
                 * 
                 */
                public List<Rezept> getGetraenk() {
                    if (getraenk == null) {
                        getraenk = new ArrayList<Rezept>();
                    }
                    return this.getraenk;
                }

                /**
                 * Gets the value of the gericht property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the gericht property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getGericht().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Rezept }
                 * 
                 * 
                 */
                public List<Rezept> getGericht() {
                    if (gericht == null) {
                        gericht = new ArrayList<Rezept>();
                    }
                    return this.gericht;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="dekoration_element" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dekorationElement"
            })
            public static class Dekoration {

                @XmlElement(name = "dekoration_element")
                protected List<Beschreibung> dekorationElement;

                /**
                 * Gets the value of the dekorationElement property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the dekorationElement property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDekorationElement().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Beschreibung }
                 * 
                 * 
                 */
                public List<Beschreibung> getDekorationElement() {
                    if (dekorationElement == null) {
                        dekorationElement = new ArrayList<Beschreibung>();
                    }
                    return this.dekorationElement;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="location" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "location"
            })
            public static class Locations {

                protected List<Beschreibung> location;

                /**
                 * Gets the value of the location property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the location property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getLocation().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Beschreibung }
                 * 
                 * 
                 */
                public List<Beschreibung> getLocation() {
                    if (location == null) {
                        location = new ArrayList<Beschreibung>();
                    }
                    return this.location;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="song" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;all>
             *                   &lt;element name="song_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                   &lt;element name="song_interpret" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
             *                 &lt;/all>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "song"
            })
            public static class Musik {

                protected List<Themes.Theme.Module.Musik.Song> song;

                /**
                 * Gets the value of the song property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the song property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSong().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Themes.Theme.Module.Musik.Song }
                 * 
                 * 
                 */
                public List<Themes.Theme.Module.Musik.Song> getSong() {
                    if (song == null) {
                        song = new ArrayList<Themes.Theme.Module.Musik.Song>();
                    }
                    return this.song;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;all>
                 *         &lt;element name="song_titel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *         &lt;element name="song_interpret" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                 *       &lt;/all>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {

                })
                public static class Song {

                    @XmlElement(name = "song_titel", required = true)
                    protected Object songTitel;
                    @XmlElement(name = "song_interpret", required = true)
                    protected Object songInterpret;
                    protected Object link;

                    /**
                     * Gets the value of the songTitel property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *     
                     */
                    public Object getSongTitel() {
                        return songTitel;
                    }

                    /**
                     * Sets the value of the songTitel property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *     
                     */
                    public void setSongTitel(Object value) {
                        this.songTitel = value;
                    }

                    /**
                     * Gets the value of the songInterpret property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *     
                     */
                    public Object getSongInterpret() {
                        return songInterpret;
                    }

                    /**
                     * Sets the value of the songInterpret property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *     
                     */
                    public void setSongInterpret(Object value) {
                        this.songInterpret = value;
                    }

                    /**
                     * Gets the value of the link property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *     
                     */
                    public Object getLink() {
                        return link;
                    }

                    /**
                     * Sets the value of the link property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *     
                     */
                    public void setLink(Object value) {
                        this.link = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="outfit" type="{}beschreibung" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "outfit"
            })
            public static class Outfits {

                protected List<Beschreibung> outfit;

                /**
                 * Gets the value of the outfit property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the outfit property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOutfit().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Beschreibung }
                 * 
                 * 
                 */
                public List<Beschreibung> getOutfit() {
                    if (outfit == null) {
                        outfit = new ArrayList<Beschreibung>();
                    }
                    return this.outfit;
                }

            }

        }

    }

}
